
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ror
  password: 1234


development:
  <<: *default
  database: music_band_search_development

test:
  <<: *default
  database: music_band_search_test

production:
  <<: *default
  database: music_band_search_production
  username: music_band_search
  password: <%= ENV["MUSIC_BAND_SEARCH_DATABASE_PASSWORD"] %>
